# Generated by Django 4.2.7 on 2024-04-01 04:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, unique=True)),
                ('time', models.CharField(choices=[('1-vaqt', '09:00-10:00'), ('2-vaqt', '10:10-11:10'), ('3-vaqt', '11:20-12:30'), ('4-vaqt', '14:00-15:00'), ('5-vaqt', '15:10-16:20'), ('6-vaqt', '16:30-17:30'), ('7-vaqt', '17:40-18:40')], max_length=50)),
                ('day', models.CharField(choices=[('Odd', 'Toq'), ('Even', 'Juft')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app.user')),
            ],
            bases=('app.user',),
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app.user')),
                ('space_id', models.CharField(max_length=6, unique=True)),
                ('avatar', models.ImageField(upload_to='media/avatars')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.group')),
            ],
            bases=('app.user',),
        ),
        migrations.AddField(
            model_name='group',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.teacher'),
        ),
    ]
